blank_issues_enabled: false
contact_links:
  - name: Vraag of idee zonder fout
    url: https://beleggerkees.nl
    about: Voor algemene vragen kun je mailen naar info@beleggerkees.nl.
  - name: Samen leren in de Community
    url: https://community.beleggerkees.nl/registreren
    about: Bespreek de methode met andere beleggers.
